const { builtinModules } = require("module")

class HeatingPump {

    static AllParams =
        [
            {"name":"APPL.CtrlAppl.sParam.state.controlMode", "sid":"State", "friendlyName":"ControlMode", "type": "number", "unit":""},
            {"name":"APPL.CtrlAppl.sParam.state.force", "sid":"State", "friendlyName":"Force", "type": "boolean", "unit":""},
            {"name":"APPL.CtrlAppl.sParam.state.msgClass", "sid":"State", "friendlyName":"MessageClass", "type": "number", "unit":""},
            {"name":"APPL.CtrlAppl.sParam.state.msgId", "sid":"State", "friendlyName":"MessageId", "type": "number", "unit":""},

            {"name":"APPL.CtrlAppl.sParam.param.operatingMode", "sid":"Params", "friendlyName":"OperatingMode", "type": "number", "unit":""},
            {"name":"APPL.CtrlAppl.sParam.param.operatingModeOld", "sid":"Params", "friendlyName":"OperatingModeOld", "type": "number", "unit":""},
            {"name":"APPL.CtrlAppl.sParam.param.setControlMode", "sid":"Params", "friendlyName":"SetControlMode", "type": "number", "unit":""},
            {"name":"APPL.CtrlAppl.sParam.param.setupModeMaxTimeS", "sid":"Params", "friendlyName":"SetupModeMaxTimeS", "type": "number", "unit":""},
            {"name":"APPL.CtrlAppl.sParam.param.systemSerialNumber", "sid":"Params", "friendlyName":"SystemSerialNumber", "type": "string", "unit":""},
            {"name":"APPL.CtrlAppl.sParam.param.systemVersion", "sid":"Params", "friendlyName":"SystemVersion", "type": "string", "unit":""},
            {"name":"APPL.CtrlAppl.sParam.param.applVersion", "sid":"Params", "friendlyName":"ApplVersion", "type": "string", "unit":""},
            {"name":"APPL.CtrlAppl.sParam.param.systemName", "sid":"Params", "friendlyName":"SystemName", "type": "string", "unit":""},
            {"name":"APPL.CtrlAppl.sParam.param.timeDayNight.start", "sid":"Params", "friendlyName":"TimeDayNightStart", "type": "number", "unit":""},
            {"name":"APPL.CtrlAppl.sParam.param.timeDayNight.stop", "sid":"Params", "friendlyName":"TimeDayNightStop", "type": "number", "unit":""},

            {"name":"APPL.CtrlAppl.sParam.options.systemSchematic", "sid":"Options", "friendlyName":"SystemSchematic", "type": "number", "unit":""},
            {"name":"APPL.CtrlAppl.sParam.options.systemNumberOfBuffers", "sid":"Options", "friendlyName":"SystemNumberOfBuffers", "type": "number", "unit":""},
            {"name":"APPL.CtrlAppl.sParam.options.systemNumberOfHotWaterTanks", "sid":"Options", "friendlyName":"SystemNumberOfHotWaterTanks", "type": "number", "unit":""},
            {"name":"APPL.CtrlAppl.sParam.options.systemNumberOfHeatingCircuits", "sid":"Options", "friendlyName":"SystemNumberOfHeatingCircuits", "type": "number", "unit":""},
            {"name":"APPL.CtrlAppl.sParam.options.systemNumberOfSolarCircuits", "sid":"Options", "friendlyName":"SystemNumberOfSolarCircuits", "type": "number", "unit":""},
            {"name":"APPL.CtrlAppl.sParam.options.systemNumberOfExtHeatRequest", "sid":"Options", "friendlyName":"SystemNumberOfExtHeatRequest", "type": "number", "unit":""},
            {"name":"APPL.CtrlAppl.sParam.options.systemNumberOfExtHeatSources", "sid":"Options", "friendlyName":"SystemNumberOfExtHeatSources", "type": "number", "unit":""},
            {"name":"APPL.CtrlAppl.sParam.options.systemNumberOfNetworkPumps", "sid":"Options", "friendlyName":"SystemNumberOfNetworkPumps", "type": "number", "unit":""},
            {"name":"APPL.CtrlAppl.sParam.options.systemNumberOfSwitchValves", "sid":"Options", "friendlyName":"SystemNumberOfSwitchValves", "type": "number", "unit":""},
            {"name":"APPL.CtrlAppl.sParam.options.systemNumberOfGenericOutputs", "sid":"Options", "friendlyName":"SystemNumberOfGenericOutputs", "type": "number", "unit":""},
            {"name":"APPL.CtrlAppl.sParam.options.systemNumberOfHeatPumps", "sid":"Options", "friendlyName":"SystemNumberOfHeatPumps", "type": "number", "unit":""},
            {"name":"APPL.CtrlAppl.sParam.options.hasOutdoorTemp", "sid":"Options", "friendlyName":"HasOutdoorTemp", "type": "string", "unit":""},
            {"name":"APPL.CtrlAppl.sParam.options.hasFlowTempSensor", "sid":"Options", "friendlyName":"HasFlowTempSensor", "type": "boolean", "unit":""},
            {"name":"APPL.CtrlAppl.sParam.options.hasPhotovoltaics", "sid":"Options", "friendlyName":"HasPhotovoltaics", "type": "boolean", "unit":""},
            {"name":"APPL.CtrlAppl.sParam.options.hasSmartGrid", "sid":"Options", "friendlyName":"HasSmartGrid", "type": "boolean", "unit":""},
            {"name":"APPL.CtrlAppl.sParam.options.hasCommonHCValve", "sid":"Options", "friendlyName":"HasCommonHCValve", "type": "boolean", "unit":""},
            {"name":"APPL.CtrlAppl.sParam.options.hasHeatRecoveryVentilation", "sid":"Options", "friendlyName":"HasHeatRecoveryVentilation", "type": "boolean", "unit":""},
      
            {"name":"APPL.CtrlAppl.sParam.operationalData.operationalTimeS", "sid":"OperationalData", "friendlyName":"OperationalTimeS", "type": "number", "unit":""},
            {"name":"APPL.CtrlAppl.sParam.operationalData.minRunTimeS", "sid":"OperationalData", "friendlyName":"MinRunTimeS", "type": "number", "unit":"s"},
            {"name":"APPL.CtrlAppl.sParam.operationalData.maxRunTimeS", "sid":"OperationalData", "friendlyName":"MaxRunTimeS", "type": "number", "unit":"s"},
            {"name":"APPL.CtrlAppl.sParam.operationalData.activationCounter", "sid":"OperationalData", "friendlyName":"ActivationCounter", "type": "number", "unit":""},
      
            {"name":"APPL.CtrlAppl.sDiagnosisData.hotWaterTank[0].setpointTemp", "sid":"Temperatures", "friendlyName":"SetpointTemp", "type": "number", "unit":"°C"},
            {"name":"APPL.CtrlAppl.sDiagnosisData.hotWaterTank[0].topTemp", "sid":"Temperatures", "friendlyName":"TopTemp", "type": "number", "unit":"°C"},
            
            {"name":"APPL.CtrlAppl.sDiagnosisData.heatCircuit[0].tempFlowSet", "sid":"Temperatures", "friendlyName":"TempFlowSet", "type": "number", "unit":"°C"},

            {"name":"APPL.CtrlAppl.sParam.heatCircuit[0].values.selectedSetTemp", "sid":"Temperatures", "friendlyName":"SelectedSetTemp", "type": "number", "unit":"°C"}, 
            {"name":"APPL.CtrlAppl.sParam.heatCircuit[0].values.flowSetTemp", "sid":"Temperatures", "friendlyName":"FlowSetTemp", "type": "number", "unit":"°C"},  
            {"name":"APPL.CtrlAppl.sDiagnosisData.tempOutdoor", "sid":"Temperatures", "friendlyName":"TempOutdoor", "type": "number", "unit":"°C"},
            {"name":"APPL.CtrlAppl.sDiagnosisData.tempFlow", "sid":"Temperatures", "friendlyName":"TempFlow", "type": "number", "unit":"°C"},
      
            {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].Compressor", "sid":"Heatpump", "friendlyName":"Compressor", "type": "number", "unit":"%"},
            {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].TempCompressorIn", "sid":"Heatpump", "friendlyName":"TempCompressorIn", "type": "number", "unit":"°C"},
            {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].TempCompressorOut", "sid":"Heatpump", "friendlyName":"TempCompressorOut", "type": "number", "unit":"°C"},
            {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].TempFlow", "sid":"Heatpump", "friendlyName":"TempFlow", "type": "number", "unit":"°C"},
            {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].TempReflux", "sid":"Heatpump", "friendlyName":"TempReflux", "type": "number", "unit":"°C"},
            {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].TempCondenserOut", "sid":"Heatpump", "friendlyName":"TempCondenserOut", "type": "number", "unit":"°C"},
            {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].LowPressure", "sid":"Heatpump", "friendlyName":"LowPressure", "type": "number", "unit":"bar"},
            {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].HighPressure", "sid":"Heatpump", "friendlyName":"HighPressure", "type": "number", "unit":"bar"}
        ]
    

    static get getAllParamNames() {
        // return HeatingPump.AllParams.State;
        return HeatingPump.AllParams.map(f=>({name: f.name}));
    }

    static ParamNames2 = 
    [
       
     
        {"name":"APPL.CtrlAppl.sParam.heatpump[0].values.COP"},
        {"name":"APPL.CtrlAppl.sParam.heatpump[0].values.heatpumpState"},
        {"name":"APPL.CtrlAppl.sParam.heatpump[0].values.heatpumpSubState"},
        {"name":"APPL.CtrlAppl.sParam.heatpump[0].values.consumingExcessEnergy"},
        {"name":"APPL.CtrlAppl.sParam.heatpump[0].values.consumedExcessEnergy"},
        {"name":"APPL.CtrlAppl.sParam.heatpump[0].values.request"},
        {"name":"APPL.CtrlAppl.sParam.heatpump[0].values.setTemp"},
        
    
        {"name":"APPL.CtrlAppl.sDiagnosisData.operatingMode"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.tempOutdoor"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.tempFlow"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatCircuit[0].operatingMode"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatCircuit[0].mixerOn"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatCircuit[0].failure"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatCircuit[0].failureCool"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatCircuit[0].type"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatCircuit[0].tempRoom"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatCircuit[0].tempOffsetRoom"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatCircuit[0].tempRoomSet"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatCircuit[0].tempRoomSetCool"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatCircuit[0].tempFlow"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatCircuit[0].tempFlowSet"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatCircuit[0].tempReflux"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatCircuit[0].dewPoint"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatCircuit[0].roomHumidity"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatCircuit[0].digitalRequest"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatCircuit[0].digitalCoolRequest"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatCircuit[0].condansateSV"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatCircuit[0].heatRequest"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatCircuit[0].heatReqTemp"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatCircuit[0].coolRequest"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatCircuit[0].coolReqTemp"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatCircuit[0].emcyCooling"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatCircuit[0].frostProtection"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatCircuit[0].useExcessEnergy"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatCircuit[0].resudialHeatUsage"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatCircuit[0].resudialCoolUsage"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatCircuit[0].pumpRequest"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatCircuit[0].pumpRequestSink"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatCircuit[0].pumpRequestSource"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatCircuit[0].heatRequestSink"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatCircuit[0].mixerOutVal"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatCircuit[0].pumpOutVal"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatCircuit[0].valveHeatCool"},
      
        {"name":"APPL.CtrlAppl.sDiagnosisData.hotWaterTank[0].operatingMode"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.hotWaterTank[0].failure"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.hotWaterTank[0].setpointTemp"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.hotWaterTank[0].topHeatRequest"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.hotWaterTank[0].legionellaProtActive"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.hotWaterTank[0].frostProtection"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.hotWaterTank[0].emcyCooling"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.hotWaterTank[0].useExcessEnergy"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.hotWaterTank[0].resudialHeatUsage"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.hotWaterTank[0].topTemp"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.hotWaterTank[0].circTemp"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.hotWaterTank[0].HXTemp"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.hotWaterTank[0].coolCellTemp"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.hotWaterTank[0].pump"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.hotWaterTank[0].circPump"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.hotWaterTank[0].dhwHeatPump"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.hotWaterTank[0].auxHeater"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.hotWaterTank[0].pumpRequest"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.hotWaterTank[0].dhwHPHeatRequest"},

        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].failure"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].failureSafetyChain"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].failureNoSafetyChain"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].failureReqSourceActuator"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].failureReqCircPump"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].failureReqNoAuxHeater"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].error"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].errorquitted"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].frostAlarm"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].locked"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].bivalenceLocked"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].forced"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].bivalenceForced"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].emcyCooling"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].excessEnergy"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].DHWheatup"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].heatpumpState"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].heatpumpSubState"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].stateTimeS"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].frostProtDefrost"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].frostProtExt"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].flushDirectHeat"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].startUpVarSpeed"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].flushTimeBelowLimit"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].heatRequestExt"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].tempHeatRequestExt"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].powerHeatRequestExt"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].tempActHeatRequestMinExt"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].coolRequestExt"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].tempCoolRequestExt"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].powerCoolRequestExt"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].tempActCoolRequestMinExt"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].heatpumpRequest"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].tempHeatPumpSet"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].excessEnergyHeat"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].excessEnergyCool"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].TempSourceIn"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].TempSourceOut"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].TempCompressorIn"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].TempCompressorOut"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].TempFlow"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].TempReflux"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].TempCondenserOut"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].TempCoolPassive"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].MagnetValveSGHX"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].MagnetValveHeat"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].MagnetValveCool"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].MagnetValveDefrost"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].ActivateCompressor"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].Compressor"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].ActivateSource"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].SourceSupply"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].Source"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].SecondSource"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].ActivateCircPump"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].CirculatingPump"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].LowPressure"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].HighPressure"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].UCompressor"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].defrostSpeedScaled"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].ActSpeedCompressor"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].ActSpeedCompressorScaled"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].MinCompSpeedScaled"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].MaxCompSpeedScaled"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].MinFreqScaled"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].deltaEnvelope"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].MaxOHEnvelope"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].MinOHEnvelope"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].OutsideEnvelope"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].EnvArea"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].RCArea"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].RC"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].tempCondCorrection"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].tempCondInvLimit"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].tempVapCorrection"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].tempVapInvLimit"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].driveStatus"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].alarmCode"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].statusRegister"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].motorFreq"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].motorCurrent"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].motorPower"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].motorVoltage"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].dcBusVoltage"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].driveTemp"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].energyMeter"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].rotorFrequency"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].dcBusRipple"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].rndvalue"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].COP"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].EnergyEfficiencyRatio"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].EnergyEfficiencyRatioCool"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].FailureSource"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].LowPressureFailure"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].HighPressureFailure"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].CompressorFailure"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].ThreePhaseDeb"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].VFDDeb"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].FailActuatorSourceDeb"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].PumpDownDeb"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].HeatSideFlowSwitchDeb"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].OilHeating"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].OilHeatingNeeded"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].CondensateHeating"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].AuxHeaterNeeded"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].AuxHeaterRefluxSV"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].AuxHeaterStartCrit"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].SourcePumpNeeded"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].SnowCoverage"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].randomInputDelay"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].TimeStampHeatPump"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].PwrCtrl.useSetTemp"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].PwrCtrl.invSetAct"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].PwrCtrl.startSecondLevel"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].PwrCtrl.calculatedPower"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].PwrCtrl.calculatedRampPower"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].PwrCtrl.lintabPower"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].HeatSpeedCtrl.tempRef"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].HeatSpeedCtrl.tempRefLimit"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].HeatSpeedCtrl.tempRefSV"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].HeatSpeedCtrl.actTempSpread"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].HeatSpeedCtrl.setTempSpread"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].HeatSpeedCtrl.freqScaled"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].SourceSpeedCtrl.tempRef"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].SourceSpeedCtrl.tempRefLimit"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].SourceSpeedCtrl.tempRefSV"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].SourceSpeedCtrl.actTempSpread"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].SourceSpeedCtrl.setTempSpread"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].SourceSpeedCtrl.freqScaled"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].powerSet"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].powerActScaled"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].TandemComp.request"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].TandemComp.setPowerScaled"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].TandemComp.state"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].TandemComp.remainingTime"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].TandemComp.TimeStampCompressorRiseEdge"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].TandemComp.useExcessEnergy"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].TimeStampCompressorRiseEdge"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].CompBool"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].CompBoolDeb"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].DefrostingTimeOut"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].ErrorDefrostCircInv"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].PassiveCoolFailure"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].ErrorCompEnv"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].suspendHRactTemp"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].suspendHRFlush"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].pumpRequestExt"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].suspendCRFlush"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].suspendCRactTemp"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].suspendAuxFlush"},
        {"name":"APPL.CtrlAppl.sDiagnosisData.heatpump[0].sinkPumpRequest"},
      
    ]
}

module.exports = HeatingPump